version: "3"
services: 

  website:
    build: ./serv
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./serv/certs:/var/www/certs"

  bot:
#     image: d2bc806cf339
    build: ./bot
    container_name: bot
    volumes:
      - ./bot:/app
#    command: exec gunicorn wuestbot:app -b 0.0.0.0:8443 -w 1 --access-logfile -
    ports:
      - "8443:8443"
