version: "3"
services: 

  website:
    build: ./serv
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./serv/certs:/var/www/certs"

  bot:
    image: python:3
    container_name: bot
    working_dir: /app
    volumes:
      - ./bot:/app
    entrypoint: /app/docker-entrypoint.sh
    ports:
      - "8443:8443"
